STAR-157 : Added commit-msg

diff --git a/resources/git-hooks/pre-commit b/resources/git-hooks/pre-commit
--- a/resources/git-hooks/pre-commit
+++ b/resources/git-hooks/pre-commit
@@ -1,5 +1,15 @@
 #!/bin/env bash
 
+local_branch="$(git rev-parse --abbrev-ref HEAD)"
+
+valid_branch_regex="^star-[0-9]+[a-z0-9_-]*$"
+
+if [[ ! $local_branch = "main" ]] && [[ ! $local_branch =~ $valid_branch_regex ]]
+then
+    echo "Your branch name is invalid, got '$local_branch', expected '$valid_branch_regex'"
+    exit 1
+fi
+
 yarn prettier:fix 
 
 yarn lint:fix
